name: Matrix Microservices IF

on:
  workflow_dispatch

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service-name: ['service-a', 'service-b', 'service-c']
    steps:
      - name: set up db instance for service-a
        if: matrix.service-name == 'service-a'
        run: echo "DB_INSTNCE=db-a:1111" >> $GITHUB_ENV
      - name: set up db instance for service-b
        if: matrix.service-name == 'service-b'
        run: echo "DB_INSTNCE=db-b:2222" >> $GITHUB_ENV
      - name: set up db instance for service-c
        if: matrix.service-name == 'service-c'
        run: echo "DB_INSTNCE=db-c:3333" >> $GITHUB_ENV
      - name: migration
        run: echo "run migration --db-instance=$DB_INSTANCE"